CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias TEXT NOT NULL,
    alias_key TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    city_id TEXT,
    can_supervise INTEGER NOT NULL DEFAULT 0 CHECK(can_supervise IN (0,1))
);
CREATE TABLE sessions (
    token_hash TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at DOUBLE PRECISION NOT NULL
);
CREATE INDEX "session_user" ON sessions(user_id);
CREATE TABLE days (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date TEXT NOT NULL,
    prayers TEXT NOT NULL,
    sunnah TEXT NOT NULL,
    dhuhr_before_blocks TEXT NOT NULL,
    version INTEGER NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY(user_id, date)
);
CREATE TABLE supervisor_children (
    supervisor_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    child_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY(supervisor_id, child_id),
    CHECK(supervisor_id != child_id)
);
CREATE INDEX supervisor_child ON supervisor_children(child_id);
CREATE TABLE supervisor_invites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supervisor_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    created_at DOUBLE PRECISION NOT NULL,
    revoked_at DOUBLE PRECISION
);
CREATE UNIQUE INDEX supervisor_active_invite ON supervisor_invites(supervisor_id) WHERE revoked_at IS NULL;
CREATE TABLE supervisor_invite_acceptances (
    invite_id BIGINT NOT NULL REFERENCES supervisor_invites(id) ON DELETE CASCADE,
    child_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    request_key TEXT NOT NULL,
    accepted_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY(child_id, request_key)
);
