CREATE TABLE app_migrations (name TEXT PRIMARY KEY);
CREATE TABLE groups (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL,
 admin_id BIGINT NOT NULL REFERENCES users(id),
 members_can_view_records INTEGER NOT NULL DEFAULT 0 CHECK(members_can_view_records IN (0,1)),
 created_at DOUBLE PRECISION NOT NULL);
CREATE TABLE group_members (
 group_id BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 created_at DOUBLE PRECISION NOT NULL, PRIMARY KEY(group_id,user_id));
CREATE INDEX group_member_user ON group_members(user_id);
CREATE TABLE group_invites (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, group_id BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
 token_hash TEXT NOT NULL UNIQUE, created_at DOUBLE PRECISION NOT NULL, revoked_at DOUBLE PRECISION);
CREATE UNIQUE INDEX group_active_invite ON group_invites(group_id) WHERE revoked_at IS NULL;
CREATE TABLE group_invite_acceptances (
 invite_id BIGINT NOT NULL REFERENCES group_invites(id),
 user_id BIGINT NOT NULL REFERENCES users(id), request_key TEXT NOT NULL,
 accepted_at DOUBLE PRECISION NOT NULL, PRIMARY KEY(user_id,request_key));

INSERT INTO groups(id,name,admin_id,created_at)
SELECT users.id,'مجموعة ' || users.alias,users.id,users.created_at FROM users
WHERE users.id IN (SELECT supervisor_id FROM supervisor_children UNION SELECT supervisor_id FROM supervisor_invites);
INSERT INTO group_members SELECT id,admin_id,created_at FROM groups;
INSERT INTO group_members SELECT supervisor_id,child_id,created_at FROM supervisor_children;
INSERT INTO group_invites SELECT id,supervisor_id,token_hash,created_at,revoked_at FROM supervisor_invites;
INSERT INTO group_invite_acceptances SELECT invite_id,child_id,request_key,accepted_at FROM supervisor_invite_acceptances;
INSERT INTO app_migrations VALUES('groups_v1');
SELECT setval(pg_get_serial_sequence('groups','id'),COALESCE((SELECT MAX(id) FROM groups),0)+1,false);
SELECT setval(pg_get_serial_sequence('group_invites','id'),COALESCE((SELECT MAX(id) FROM group_invites),0)+1,false);
